### ISSUE TITLE
Scaffold Project

### ISSUE THREAD

**Issue by lepsalex** [icgc-argo/workflow-graph-manager#2]
* make it real
* plan for realness: https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=Graph+Manager+Design%3A+RabbitMQ+Reporting+and+Queue+Management

### Expected Outcome
* Reactor all the things
* GQL server with Apollo federation
* Entities as defined in plan for realness
* Docker + Jenkins

**Comment by rosibaj** [comment]
https://github.com/icgc-argo/workflow-graph-manager/tree/init 

was done here, not Pr'd before break.  clean-up in new year
