### ISSUE TITLE
Evaluate Rabbit MQ Management API 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-graph-manager#8]
- make sure the provided API can complete the queries we need 
- if not, come up with a contingency solution that would allow us to interact with Rabbit MQ
- investigate whether this is deployed in our current environment. 

https://www.rabbitmq.com/management.html

**Comment by lepsalex** [comment]
The main concerns I had around using the RMQ Management API centered around consistency and random access (messages), after further investigation these concerns can be mitigated within Graph Manager following the approach outlined here: https://wiki.oicr.on.ca/pages/viewpage.action?pageId=154539008
